# NumPy Reference

In [ ]:
import numpy as np

In [ ]:
np.__version__

In [ ]:
a=np.array([1,2,3],dtype='int16')

In [ ]:
a

In [ ]:
b=np.array([[9.0,8.0,7.0,6.0],[5.0,4.0,3.0,2.0]])

In [ ]:
b

In [ ]:
print(type(a))
print(type(b))

In [ ]:
b.ndim

In [ ]:
#Get Shape
b.shape

In [ ]:
#Get type
a.dtype

In [ ]:
#Get Size
print(a.itemsize)
b.itemsize


In [ ]:
#Get total size
print(a.size*a.itemsize)
print(a.nbytes)
print(b.nbytes)

# Accessing, Changing specific elements, rows, columns, etc.

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
a

In [ ]:
a.shape

In [ ]:
#Get a specific element [r,c]
a[1,5]

In [ ]:
a[1,-2]

In [ ]:
#Get a specific row
a[0,:]

In [ ]:
a[:,2]

In [ ]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

In [ ]:
a[1,5]=20
a

In [ ]:
a[:,2]=5
a

### 3-D exapmle

In [ ]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

In [ ]:
#Get specific element (work outside in)
c[0,1,1]
 # 1st set, then another array with 2 rows 2 columns. We are going to the second row,second column of the first array

# Initializing Different types of Arrays

In [ ]:
#All 0's matrix
print(np.zeros(10))
np.zeros((2,2,2,2))

In [ ]:
#All 1's matrix
np.ones((4,2,2),dtype='int32')

In [ ]:
#All x's (x can be any number)
np.full((2,3,2),553,dtype='float32')

In [ ]:
#Replace a existing array with  a number
np.full(a.shape,3)

In [ ]:
#Random decimal number
np.random.rand(4,2)

In [ ]:
#Replace existing array with a random number
np.random.random_sample(b.shape)

In [ ]:
#Random integer values
np.random.randint(-10,10,size=(3,3))

In [ ]:
#Identity Matrix
np.identity(6)

In [ ]:
arr=np.array([[1,2,3]])
a1=np.repeat(arr,3,axis=0)
a2=np.repeat(arr,3,axis=1)
print(a1)
print('')
print(a2)

# Assignment 1:
## Make this array without explicitly assigning the value to each element
### [1 1 1 1 1]
### [1 0 0 0 1]
### [1 0 9 0 1]
### [1 0 0 0 1]
### [1 1 1 1 1]

In [ ]:
#Solution
new=np.ones((5,5),dtype='int32')
rep=np.zeros((3,3), dtype='int32')
rep[1,1]=9
new[1:4,1:4]=rep
print(new)

In [ ]:
#Be careful when copying arrays
a=np.array([1,2,3])
b=a
print(a)
print(b)
b[0]=-9999
print(a)
print(b)
#Here the reference points to the real array and thus the change occurs in both the arrays

In [ ]:
a=np.array([1,2,3])
b=a.copy()
print(a)
print(b)
b[0]=-9999
print(a)
print(b)
#Here only value in array b is changed

# Mathematics

In [ ]:
m=np.array([1,2,3,4])
print(m)

In [ ]:
m+2

In [ ]:
m-2

In [ ]:
m/2

In [ ]:
n=np.array([1,0,1,0])
m+n

In [ ]:
m**2

In [ ]:
#Taking the sine
np.sin(m)

In [ ]:
#Taking cosine
np.cos(n)

# Linear Algebra

# Reference documentations
[Click here to go](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
## What you can perform?
### Determinant
### Trace
### Singular Vector Decomposition
### Eigenvalues
### Matrix Norm
### Inverse
### Etc..


In [ ]:
a=np.full((2,3),1)
print(a)

In [ ]:
b=np.full((3,2),2)
print(b)

In [ ]:
#Mu]atrix Multiplication
np.matmul(a,b)

In [ ]:
#Find the determinant
c=np.identity(3)
np.linalg.det(c)

# Statistics


In [ ]:
stats=np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats,axis=0)

In [ ]:
np.sum(stats,axis=0)

# Reorganizing Arrays

In [ ]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape(2,2,2)
print(after)

In [ ]:
#Vertical Stacking Vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

In [ ]:
#Horizontal Stacking Vectors
h1=np.ones([2,6])
h2=np.zeros([2,4])
np.hstack([h1,h2])

# Miscellaneous

In [ ]:
file_data=np.genfromtxt('data.txt',delimiter=',')
file_data=file_data.astype('int32')
file_data

# Boolean Masking & Advanced Indexing

In [ ]:
file_data>10
#Finds out whether the condition is satisfied or not

In [ ]:
file_data[file_data>10]
#Finds out and prints a list of those values that are satisfying the conditions

In [ ]:
#Indexing a list with NumPy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

In [ ]:
print(np.any(file_data>10, axis=0)) 
#Whether any number is greater than 10 columnwise
print(np.any(file_data>10, axis=1)) 
#Whether any number is greater than 10 rowwise
#Axis=0:Column
#Axis=1:Row


In [ ]:
np.all(file_data>10,axis=1)
#Rowwise, the third and last row have all data greater than 10

In [ ]:
((file_data>10) & (file_data<15))

In [ ]:
(~(file_data>10) & (file_data<15))

# Assignment 2:
## In a 5*6 matrix with natural numbers, how will you index the numbers:
## A:11,12,16,17
-----------
## B:2,8,14,20

In [ ]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

In [ ]:
#Solution A:
a[2:4,0:2]

In [ ]:
#Solution B:
a[[0,1,2,3],[1,2,3,4]]

In [ ]:
a[[0,4,5],3:]