In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.3'

In [3]:
arr=np.random.rand(20,20)

In [4]:
arr

array([[3.96276211e-01, 9.13503658e-01, 4.60480266e-01, 1.68603749e-01,
        2.82188082e-01, 6.93494705e-01, 6.34990698e-01, 3.35648012e-01,
        9.02326392e-01, 9.47167891e-01, 3.20371575e-01, 1.40776254e-01,
        6.43538996e-01, 9.69055734e-01, 3.67926070e-01, 9.48367083e-03,
        2.36789230e-01, 9.27778570e-01, 6.98172052e-01, 2.27173740e-01],
       [4.30466641e-01, 2.92830912e-01, 3.76102442e-01, 7.61680108e-01,
        1.73521530e-01, 8.73771864e-01, 9.42619117e-01, 5.30751315e-01,
        9.92676497e-01, 5.89632256e-01, 8.33208771e-01, 7.46397741e-01,
        7.78298654e-01, 1.47350878e-01, 4.37078652e-01, 1.95352501e-01,
        7.07484105e-04, 7.25609153e-01, 2.74434445e-01, 8.68246611e-01],
       [3.13206452e-01, 2.52057551e-01, 2.74939718e-01, 5.50423382e-01,
        7.40440535e-01, 7.53495989e-03, 8.60028285e-01, 3.34455517e-01,
        8.94628739e-01, 2.26123654e-01, 3.09817406e-01, 3.98196084e-01,
        9.88537200e-01, 4.07721334e-01, 3.84046671e-01, 4.2712

In [5]:
arr[arr>0.8]

array([0.91350366, 0.90232639, 0.94716789, 0.96905573, 0.92777857,
       0.87377186, 0.94261912, 0.9926765 , 0.83320877, 0.86824661,
       0.86002829, 0.89462874, 0.9885372 , 0.83252624, 0.9461478 ,
       0.89395545, 0.93779002, 0.86260475, 0.91783957, 0.97687428,
       0.94944105, 0.83137147, 0.93970027, 0.81612151, 0.81181245,
       0.95001138, 0.8589797 , 0.87931967, 0.80003351, 0.82634183,
       0.94880195, 0.92950689, 0.85938697, 0.92132243, 0.92521638,
       0.96881515, 0.86112286, 0.98135588, 0.93446802, 0.8539495 ,
       0.86102962, 0.92477909, 0.86847625, 0.98876751, 0.87259186,
       0.85770015, 0.82495081, 0.8454157 , 0.91683561, 0.95994275,
       0.84286536, 0.8569199 , 0.89312735, 0.88284798, 0.87999912,
       0.81489509, 0.85527402, 0.93808047, 0.97711727, 0.96958748,
       0.96990191, 0.84586322, 0.88947854, 0.94576079, 0.92786349,
       0.88143492, 0.95733952, 0.83476371, 0.81074454, 0.91493516,
       0.82802604, 0.97216564, 0.84966296, 0.82947922, 0.89240

In [6]:
arr[arr<0.2]

array([0.16860375, 0.14077625, 0.00948367, 0.17352153, 0.14735088,
       0.1953525 , 0.00070748, 0.00753496, 0.17596875, 0.04481276,
       0.19711528, 0.16460826, 0.07120155, 0.0034309 , 0.00654075,
       0.07268382, 0.01597029, 0.11104558, 0.08183836, 0.03748447,
       0.11059305, 0.11202504, 0.15820705, 0.04215571, 0.14160664,
       0.1358018 , 0.18813274, 0.05009692, 0.02187494, 0.16171095,
       0.14543374, 0.02006627, 0.09981586, 0.01176992, 0.00536901,
       0.01687247, 0.10624043, 0.0947784 , 0.13410713, 0.16115574,
       0.18871628, 0.10972542, 0.17074334, 0.04112956, 0.11955253,
       0.12184974, 0.1655288 , 0.094727  , 0.15925048, 0.14753328,
       0.11441367, 0.19840899, 0.10183529, 0.176294  , 0.03405369,
       0.09237962, 0.08441173, 0.170844  , 0.07723847, 0.0279637 ,
       0.12431364, 0.10323431, 0.00893537, 0.03766525, 0.14871675,
       0.10386258, 0.17008604, 0.05678739, 0.13837176, 0.15484103,
       0.00045607, 0.10470315, 0.10624962, 0.16469446, 0.09838

In [7]:
arr[arr<0.2 or arr>0.8]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Analysing the error:
### ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [8]:
selection=np.logical_or(arr<0.2,arr>0.8)

In [9]:
arr[selection]

array([9.13503658e-01, 1.68603749e-01, 9.02326392e-01, 9.47167891e-01,
       1.40776254e-01, 9.69055734e-01, 9.48367083e-03, 9.27778570e-01,
       1.73521530e-01, 8.73771864e-01, 9.42619117e-01, 9.92676497e-01,
       8.33208771e-01, 1.47350878e-01, 1.95352501e-01, 7.07484105e-04,
       8.68246611e-01, 7.53495989e-03, 8.60028285e-01, 8.94628739e-01,
       9.88537200e-01, 8.32526244e-01, 1.75968749e-01, 4.48127565e-02,
       1.97115282e-01, 1.64608257e-01, 9.46147804e-01, 8.93955449e-01,
       7.12015501e-02, 9.37790020e-01, 3.43090421e-03, 6.54074868e-03,
       7.26838156e-02, 1.59702898e-02, 1.11045583e-01, 8.62604745e-01,
       8.18383641e-02, 9.17839567e-01, 3.74844703e-02, 1.10593049e-01,
       1.12025040e-01, 9.76874280e-01, 9.49441046e-01, 1.58207048e-01,
       4.21557123e-02, 1.41606642e-01, 8.31371469e-01, 9.39700267e-01,
       1.35801803e-01, 8.16121508e-01, 8.11812451e-01, 9.50011382e-01,
       1.88132741e-01, 8.58979697e-01, 5.00969209e-02, 2.18749375e-02,
      