# NumPy Reference

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.3'

In [3]:
a=np.array([1,2,3],dtype='int16')

In [4]:
a

array([1, 2, 3], dtype=int16)

In [5]:
b=np.array([[9.0,8.0,7.0,6.0],[5.0,4.0,3.0,2.0]])

In [6]:
b

array([[9., 8., 7., 6.],
       [5., 4., 3., 2.]])

In [7]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
b.ndim

2

In [9]:
#Get Shape
b.shape

(2, 4)

In [10]:
#Get type
a.dtype

dtype('int16')

In [11]:
#Get Size
print(a.itemsize)
b.itemsize


2


8

In [12]:
#Get total size
print(a.size*a.itemsize)
print(a.nbytes)
print(b.nbytes)

6
6
64


# Accessing, Changing specific elements, rows, columns, etc.

In [13]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [14]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
a.shape

(2, 7)

In [16]:
#Get a specific element [r,c]
a[1,5]

13

In [17]:
a[1,-2]

13

In [18]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
a[:,2]

array([ 3, 10])

In [20]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [21]:
a[1,5]=20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [22]:
a[:,2]=5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

### 3-D exapmle

In [23]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
#Get specific element (work outside in)
c[0,1,1]
 # 1st set, then another array with 2 rows 2 columns. We are going to the second row,second column of the first array

4

# Initializing Different types of Arrays

In [25]:
#All 0's matrix
print(np.zeros(10))
np.zeros((2,2,2,2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [26]:
#All 1's matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [27]:
#All x's (x can be any number)
np.full((2,3,2),553,dtype='float32')

array([[[553., 553.],
        [553., 553.],
        [553., 553.]],

       [[553., 553.],
        [553., 553.],
        [553., 553.]]], dtype=float32)

In [28]:
#Replace a existing array with  a number
np.full(a.shape,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [29]:
#Random decimal number
np.random.rand(4,2)

array([[0.2703174 , 0.73435487],
       [0.36138748, 0.54734266],
       [0.01215306, 0.73487124],
       [0.13660354, 0.48471597]])

In [30]:
#Replace existing array with a random number
np.random.random_sample(b.shape)

array([[0.87737321, 0.93023764, 0.1599989 , 0.79968663],
       [0.18282769, 0.53211451, 0.49987671, 0.56176357]])

In [31]:
#Random integer values
np.random.randint(-10,10,size=(3,3))

array([[-4,  8, -1],
       [ 1,  0, -6],
       [ 7, -8, -4]])

In [32]:
#Identity Matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
arr=np.array([[1,2,3]])
a1=np.repeat(arr,3,axis=0)
a2=np.repeat(arr,3,axis=1)
print(a1)
print('')
print(a2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 1 1 2 2 2 3 3 3]]


# Assignment 1:
## Make this array without explicitly assigning the value to each element
### [1 1 1 1 1]
### [1 0 0 0 1]
### [1 0 9 0 1]
### [1 0 0 0 1]
### [1 1 1 1 1]

In [34]:
#Solution
new=np.ones((5,5),dtype='int32')
rep=np.zeros((3,3), dtype='int32')
rep[1,1]=9
new[1:4,1:4]=rep
print(new)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [35]:
#Be careful when copying arrays
a=np.array([1,2,3])
b=a
print(a)
print(b)
b[0]=-9999
print(a)
print(b)
#Here the reference points to the real array and thus the change occurs in both the arrays

[1 2 3]
[1 2 3]
[-9999     2     3]
[-9999     2     3]


In [36]:
a=np.array([1,2,3])
b=a.copy()
print(a)
print(b)
b[0]=-9999
print(a)
print(b)
#Here only value in array b is changed

[1 2 3]
[1 2 3]
[1 2 3]
[-9999     2     3]


# Mathematics

In [37]:
m=np.array([1,2,3,4])
print(m)

[1 2 3 4]


In [38]:
m+2

array([3, 4, 5, 6])

In [39]:
m-2

array([-1,  0,  1,  2])

In [40]:
m/2

array([0.5, 1. , 1.5, 2. ])

In [41]:
n=np.array([1,0,1,0])
m+n

array([2, 2, 4, 4])

In [42]:
m**2

array([ 1,  4,  9, 16], dtype=int32)

In [43]:
#Taking the sine
np.sin(m)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [44]:
#Taking cosine
np.cos(n)

array([0.54030231, 1.        , 0.54030231, 1.        ])

# Linear Algebra

# Reference documentations
[Click here to go](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
## What you can perform?
### Determinant
### Trace
### Singular Vector Decomposition
### Eigenvalues
### Matrix Norm
### Inverse
### Etc..


In [45]:
a=np.full((2,3),1)
print(a)

[[1 1 1]
 [1 1 1]]


In [46]:
b=np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [47]:
#Mu]atrix Multiplication
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [48]:
#Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

# Statistics


In [49]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.min(stats,axis=0)

array([1, 2, 3])

In [51]:
np.sum(stats,axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [52]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
#Vertical Stacking Vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
#Horizontal Stacking Vectors
h1=np.ones([2,6])
h2=np.zeros([2,4])
np.hstack([h1,h2])

array([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.]])

# Miscellaneous

In [55]:
file_data=np.genfromtxt('data_numpy.ipynb.txt',delimiter=',')
file_data=file_data.astype('int32')
file_data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Boolean Masking & Advanced Indexing

In [56]:
file_data>10
#Finds out whether the condition is satisfied or not

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [57]:
file_data[file_data>10]
#Finds out and prints a list of those values that are satisfying the conditions

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
#Indexing a list with NumPy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [59]:
print(np.any(file_data>10, axis=0)) 
#Whether any number is greater than 10 columnwise
print(np.any(file_data>10, axis=1)) 
#Whether any number is greater than 10 rowwise
#Axis=0:Column
#Axis=1:Row


[ True  True  True  True  True]
[False False  True  True]


In [60]:
np.all(file_data>10,axis=1)
#Rowwise, the third and last row have all data greater than 10

array([False, False,  True,  True])

In [61]:
((file_data>10) & (file_data<15))

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [62]:
(~(file_data>10) & (file_data<15))

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# Assignment 2:
## In a 5*6 matrix with natural numbers, how will you index the numbers:
## A:11,12,16,17
-----------
## B:2,8,14,20

In [63]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [64]:
#Solution A:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [65]:
#Solution B:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [66]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])